version: '3'

services:

  php8:
    hostname: localhost
    image: oberd/php-8.1-apache:latest
    ports:
      - 80:80
    volumes:
      - ${PWD}/:/var/www/html/
    depends_on:
      - mailcatcher

  mailcatcher:
    image: dockage/mailcatcher:0.8.2
    ports:
      - 82:1080
      - 1027:1025